"""
Static/in-memory SRD data provider with core D&D 5e reference data.
"""
from app.services.srd.models import SRDSpell, SRDMonster, SRDEquipment, SRDClass, SRDRace

# ============================================================================
# SPELLS (25+ common spells)
# ============================================================================

srd_spells: list[SRDSpell] = [
    # Cantrips (Level 0)
    SRDSpell(
        name="Fire Bolt",
        level=0,
        school="Evocation",
        casting_time="1 action",
        range="120 feet",
        components=["V", "S"],
        duration="Instantaneous",
        description="You hurl a mote of fire at a creature or flammable object within range.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Mage Hand",
        level=0,
        school="Conjuration",
        casting_time="1 action",
        range="30 feet",
        components=["V", "S"],
        duration="Concentration, up to 1 minute",
        description="A spectral, floating hand appears at a point of your choice within range.",
        classes=["Bard", "Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Light",
        level=0,
        school="Evocation",
        casting_time="1 action",
        range="Touch",
        components=["V", "M"],
        duration="1 hour",
        description="You touch an object that is no larger than 10 feet in any dimension.",
        classes=["Bard", "Cleric", "Sorcerer", "Wizard"],
    ),
    # Level 1
    SRDSpell(
        name="Magic Missile",
        level=1,
        school="Evocation",
        casting_time="1 action",
        range="120 feet",
        components=["V", "S"],
        duration="Instantaneous",
        description="You create three glowing darts of magical force. Each dart hits a creature of your choice.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Cure Wounds",
        level=1,
        school="Evocation",
        casting_time="1 action",
        range="Touch",
        components=["V", "S"],
        duration="Instantaneous",
        description="A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.",
        classes=["Bard", "Cleric", "Druid"],
    ),
    SRDSpell(
        name="Shield",
        level=1,
        school="Abjuration",
        casting_time="1 reaction",
        range="Self",
        components=["V", "S"],
        duration="1 round",
        description="An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Sleep",
        level=1,
        school="Enchantment",
        casting_time="1 action",
        range="90 feet",
        components=["V", "S", "M"],
        duration="1 minute",
        description="This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect.",
        classes=["Bard", "Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Identify",
        level=1,
        school="Divination",
        casting_time="1 minute",
        range="Touch",
        components=["V", "S", "M"],
        duration="Instantaneous",
        description="You choose one object that you must touch throughout the casting of this spell.",
        classes=["Bard", "Cleric", "Wizard"],
    ),
    SRDSpell(
        name="Mage Armor",
        level=1,
        school="Abjuration",
        casting_time="1 action",
        range="Touch",
        components=["V", "S", "M"],
        duration="8 hours",
        description="You touch a willing creature who isn't wearing armor, and a protective magical force surrounds it.",
        classes=["Sorcerer", "Wizard"],
    ),
    # Level 2
    SRDSpell(
        name="Magic Weapon",
        level=2,
        school="Transmutation",
        casting_time="1 bonus action",
        range="Touch",
        components=["V", "S"],
        duration="Concentration, up to 1 hour",
        description="You touch a nonmagical weapon. Until the spell ends, that weapon becomes magical and has a +1 bonus.",
        classes=["Paladin", "Wizard"],
    ),
    SRDSpell(
        name="Scorching Ray",
        level=2,
        school="Evocation",
        casting_time="1 action",
        range="120 feet",
        components=["V", "S"],
        duration="Instantaneous",
        description="A line of roaring flame springs from your hand in a direction you choose over a ground range you specify.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Mirror Image",
        level=2,
        school="Illusion",
        casting_time="1 action",
        range="Self",
        components=["V", "S"],
        duration="Concentration, up to 1 minute",
        description="Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Invisibility",
        level=2,
        school="Illusion",
        casting_time="1 action",
        range="Touch",
        components=["V", "S", "M"],
        duration="Concentration, up to 1 hour",
        description="A creature you touch becomes invisible until the spell ends.",
        classes=["Bard", "Sorcerer", "Wizard"],
    ),
    # Level 3
    SRDSpell(
        name="Fireball",
        level=3,
        school="Evocation",
        casting_time="1 action",
        range="150 feet",
        components=["V", "S", "M"],
        duration="Instantaneous",
        description="A bright streak flashes from your pointing finger to a point you choose within range. Each creature in that area must make a Dexterity saving throw.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Lightning Bolt",
        level=3,
        school="Evocation",
        casting_time="1 action",
        range="Self (100-foot line)",
        components=["V", "S", "M"],
        duration="Instantaneous",
        description="A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Counterspell",
        level=3,
        school="Abjuration",
        casting_time="1 reaction",
        range="60 feet",
        components=["S"],
        duration="Instantaneous",
        description="You attempt to interrupt a creature in the process of casting a spell.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Haste",
        level=3,
        school="Transmutation",
        casting_time="1 action",
        range="30 feet",
        components=["V", "S", "M"],
        duration="Concentration, up to 1 minute",
        description="Choose a willing creature that you can see within range. Until the spell ends, the creature's speed is doubled.",
        classes=["Sorcerer", "Wizard"],
    ),
    # Level 4
    SRDSpell(
        name="Greater Invisibility",
        level=4,
        school="Illusion",
        casting_time="1 action",
        range="Touch",
        components=["V", "S"],
        duration="Concentration, up to 1 minute",
        description="You or a creature you touch becomes invisible until the spell ends.",
        classes=["Bard", "Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Stone Shape",
        level=4,
        school="Transmutation",
        casting_time="1 action",
        range="Touch",
        components=["V", "S", "M"],
        duration="Instantaneous",
        description="You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension.",
        classes=["Cleric", "Druid", "Wizard"],
    ),
    # Level 5
    SRDSpell(
        name="Cone of Cold",
        level=5,
        school="Evocation",
        casting_time="1 action",
        range="Self (60-foot cone)",
        components=["V", "S", "M"],
        duration="Instantaneous",
        description="A blast of cold air springs from your hands. Each creature in a 60-foot cone must make a Constitution saving throw.",
        classes=["Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Hold Monster",
        level=5,
        school="Enchantment",
        casting_time="1 action",
        range="90 feet",
        components=["V", "S", "M"],
        duration="Concentration, up to 1 minute",
        description="Choose a creature that you can see within range. The creature must succeed on a Wisdom saving throw or be paralyzed.",
        classes=["Bard", "Sorcerer", "Wizard"],
    ),
    SRDSpell(
        name="Telekinesis",
        level=5,
        school="Transmutation",
        casting_time="1 action",
        range="60 feet",
        components=["V", "S"],
        duration="Concentration, up to 10 minutes",
        description="You gain the ability to move or manipulate creatures or objects by thought.",
        classes=["Sorcerer", "Wizard"],
    ),
]

# ============================================================================
# MONSTERS (20+ common creatures)
# ============================================================================

srd_monsters: list[SRDMonster] = [
    SRDMonster(
        name="Goblin",
        size="Small",
        type="Humanoid",
        alignment="Chaotic Evil",
        ac=15,
        hp=7,
        speed="30 ft.",
        strength=8,
        dexterity=14,
        constitution=10,
        intelligence=10,
        wisdom=8,
        charisma=8,
        challenge_rating=0.25,
        actions="Scimitar. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.",
    ),
    SRDMonster(
        name="Skeleton",
        size="Medium",
        type="Undead",
        alignment="Chaotic Evil",
        ac=12,
        hp=13,
        speed="30 ft.",
        strength=10,
        dexterity=14,
        constitution=15,
        intelligence=6,
        wisdom=8,
        charisma=5,
        challenge_rating=0.25,
        actions="Shortsword. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
    ),
    SRDMonster(
        name="Zombie",
        size="Medium",
        type="Undead",
        alignment="Chaotic Evil",
        ac=8,
        hp=22,
        speed="20 ft.",
        strength=13,
        dexterity=6,
        constitution=16,
        intelligence=3,
        wisdom=6,
        charisma=5,
        challenge_rating=0.25,
        actions="Slam. Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) bludgeoning damage.",
    ),
    SRDMonster(
        name="Orc",
        size="Medium",
        type="Humanoid",
        alignment="Chaotic Evil",
        ac=13,
        hp=15,
        speed="30 ft.",
        strength=16,
        dexterity=12,
        constitution=16,
        intelligence=7,
        wisdom=11,
        charisma=10,
        challenge_rating=0.5,
        actions="Greataxe. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage.",
    ),
    SRDMonster(
        name="Kobold",
        size="Small",
        type="Humanoid",
        alignment="Chaotic Evil",
        ac=12,
        hp=5,
        speed="30 ft.",
        strength=7,
        dexterity=15,
        constitution=9,
        intelligence=8,
        wisdom=7,
        charisma=8,
        challenge_rating=0.125,
        actions="Dagger. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage.",
    ),
    SRDMonster(
        name="Bandit",
        size="Medium",
        type="Humanoid",
        alignment="Chaotic Evil",
        ac=12,
        hp=11,
        speed="30 ft.",
        strength=11,
        dexterity=16,
        constitution=10,
        intelligence=10,
        wisdom=11,
        charisma=10,
        challenge_rating=0.125,
        actions="Shortsword. Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage.",
    ),
    SRDMonster(
        name="Giant Spider",
        size="Large",
        type="Beast",
        alignment="Unaligned",
        ac=14,
        hp=26,
        speed="30 ft., climb 30 ft.",
        strength=14,
        dexterity=16,
        constitution=13,
        intelligence=2,
        wisdom=11,
        charisma=4,
        challenge_rating=1,
        actions="Bite. Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 7 (1d10 + 2) piercing damage.",
    ),
    SRDMonster(
        name="Wolf",
        size="Medium",
        type="Beast",
        alignment="Unaligned",
        ac=13,
        hp=11,
        speed="40 ft.",
        strength=12,
        dexterity=15,
        constitution=13,
        intelligence=3,
        wisdom=12,
        charisma=6,
        challenge_rating=0.25,
        actions="Bite. Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) piercing damage.",
    ),
    SRDMonster(
        name="Brown Bear",
        size="Large",
        type="Beast",
        alignment="Unaligned",
        ac=11,
        hp=34,
        speed="40 ft.",
        strength=19,
        dexterity=10,
        constitution=16,
        intelligence=2,
        wisdom=12,
        charisma=7,
        challenge_rating=1,
        actions="Bite. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.",
    ),
    SRDMonster(
        name="Goblin King",
        size="Small",
        type="Humanoid",
        alignment="Chaotic Evil",
        ac=17,
        hp=27,
        speed="30 ft.",
        strength=10,
        dexterity=16,
        constitution=11,
        intelligence=12,
        wisdom=11,
        charisma=14,
        challenge_rating=2,
        actions="Scimitar. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.",
    ),
    SRDMonster(
        name="Troll",
        size="Large",
        type="Giant",
        alignment="Chaotic Evil",
        ac=15,
        hp=84,
        speed="30 ft.",
        strength=18,
        dexterity=13,
        constitution=20,
        intelligence=7,
        wisdom=8,
        charisma=7,
        challenge_rating=5,
        actions="Bite. Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage.",
    ),
    SRDMonster(
        name="Dragon",
        size="Huge",
        type="Dragon",
        alignment="Chaotic Evil",
        ac=19,
        hp=195,
        speed="40 ft., fly 80 ft.",
        strength=23,
        dexterity=10,
        constitution=21,
        intelligence=16,
        wisdom=13,
        charisma=19,
        challenge_rating=8,
        actions="Bite. Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 16 (2d10 + 5) piercing damage.",
    ),
    SRDMonster(
        name="Lich",
        size="Medium",
        type="Undead",
        alignment="Chaotic Evil",
        ac=17,
        hp=135,
        speed="0 ft., fly 120 ft.",
        strength=11,
        dexterity=16,
        constitution=16,
        intelligence=20,
        wisdom=14,
        charisma=16,
        challenge_rating=12,
        actions="Paralyzing Touch. Melee Spell Attack: +12 to hit, reach 5 ft., one target. Hit: 10 (3d6) cold damage.",
    ),
    SRDMonster(
        name="Ogre",
        size="Large",
        type="Giant",
        alignment="Chaotic Evil",
        ac=11,
        hp=59,
        speed="40 ft.",
        strength=19,
        dexterity=8,
        constitution=16,
        intelligence=5,
        wisdom=7,
        charisma=7,
        challenge_rating=2,
        actions="Greatclub. Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage.",
    ),
    SRDMonster(
        name="Goblin Shaman",
        size="Small",
        type="Humanoid",
        alignment="Chaotic Evil",
        ac=15,
        hp=22,
        speed="30 ft.",
        strength=8,
        dexterity=14,
        constitution=11,
        intelligence=10,
        wisdom=14,
        charisma=8,
        challenge_rating=1,
        actions="Quarterstaff. Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d6 - 1) bludgeoning damage.",
    ),
    SRDMonster(
        name="Ghoul",
        size="Medium",
        type="Undead",
        alignment="Chaotic Evil",
        ac=12,
        hp=22,
        speed="30 ft.",
        strength=13,
        dexterity=15,
        constitution=10,
        intelligence=7,
        wisdom=10,
        charisma=6,
        challenge_rating=1,
        actions="Bite. Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage.",
    ),
    SRDMonster(
        name="Vampire",
        size="Medium",
        type="Undead",
        alignment="Chaotic Evil",
        ac=16,
        hp=144,
        speed="0 ft., fly 120 ft.",
        strength=18,
        dexterity=18,
        constitution=18,
        intelligence=17,
        wisdom=15,
        charisma=18,
        challenge_rating=13,
        actions="Bite. Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage, and the target must succeed.",
    ),
]

# ============================================================================
# EQUIPMENT (20+ common items)
# ============================================================================

srd_equipment: list[SRDEquipment] = [
    # Weapons
    SRDEquipment(
        name="Longsword",
        category="Weapons",
        cost="15 gp",
        weight=3.0,
        properties="Versatile",
    ),
    SRDEquipment(
        name="Shortsword",
        category="Weapons",
        cost="10 gp",
        weight=2.0,
        properties="Finesse, Light",
    ),
    SRDEquipment(
        name="Greataxe",
        category="Weapons",
        cost="30 gp",
        weight=7.0,
        properties="Heavy, Two-handed",
    ),
    SRDEquipment(
        name="Dagger",
        category="Weapons",
        cost="2 gp",
        weight=1.0,
        properties="Finesse, Light, Thrown",
    ),
    SRDEquipment(
        name="Shortbow",
        category="Weapons",
        cost="25 gp",
        weight=2.0,
        properties="Ammunition, Two-handed",
    ),
    SRDEquipment(
        name="Longbow",
        category="Weapons",
        cost="50 gp",
        weight=3.0,
        properties="Ammunition, Heavy, Two-handed",
    ),
    SRDEquipment(
        name="Crossbow, hand",
        category="Weapons",
        cost="75 gp",
        weight=3.0,
        properties="Ammunition, Light",
    ),
    SRDEquipment(
        name="Warhammer",
        category="Weapons",
        cost="15 gp",
        weight=2.0,
        properties="Versatile",
    ),
    SRDEquipment(
        name="Quarterstaff",
        category="Weapons",
        cost="2 sp",
        weight=4.0,
        properties="Versatile",
    ),
    SRDEquipment(
        name="Rapier",
        category="Weapons",
        cost="25 gp",
        weight=2.0,
        properties="Finesse",
    ),
    # Armor
    SRDEquipment(
        name="Leather Armor",
        category="Armor",
        cost="5 gp",
        weight=10.0,
        properties="Light Armor",
    ),
    SRDEquipment(
        name="Chain Mail",
        category="Armor",
        cost="75 gp",
        weight=55.0,
        properties="Heavy Armor",
    ),
    SRDEquipment(
        name="Plate Armor",
        category="Armor",
        cost="1500 gp",
        weight=65.0,
        properties="Heavy Armor",
    ),
    SRDEquipment(
        name="Shield",
        category="Armor",
        cost="10 gp",
        weight=6.0,
        properties="Armor",
    ),
    SRDEquipment(
        name="Helmet",
        category="Armor",
        cost="10 gp",
        weight=1.0,
        properties="Armor",
    ),
    # Adventuring Gear
    SRDEquipment(
        name="Bedroll",
        category="Adventuring Gear",
        cost="1 gp",
        weight=7.0,
        properties="Bedding",
    ),
    SRDEquipment(
        name="Rope",
        category="Adventuring Gear",
        cost="1 gp",
        weight=1.0,
        properties="50 feet",
    ),
    SRDEquipment(
        name="Backpack",
        category="Adventuring Gear",
        cost="2 gp",
        weight=5.0,
        properties="Container",
    ),
    SRDEquipment(
        name="Torch",
        category="Adventuring Gear",
        cost="1 cp",
        weight=1.0,
        properties="Light source",
    ),
    SRDEquipment(
        name="Waterskin",
        category="Adventuring Gear",
        cost="5 sp",
        weight=1.0,
        properties="Container",
    ),
]

# ============================================================================
# CLASSES (All 12 SRD classes)
# ============================================================================

srd_classes: list[SRDClass] = [
    SRDClass(
        name="Barbarian",
        hit_die=12,
        primary_ability="Strength",
        saving_throws=["Strength", "Constitution"],
        proficiencies=["simple weapons", "melee weapons"],
    ),
    SRDClass(
        name="Bard",
        hit_die=8,
        primary_ability="Charisma",
        saving_throws=["Charisma", "Dexterity"],
        proficiencies=["simple weapons", "hand crossbows", "longswords", "rapiers", "shortswords"],
    ),
    SRDClass(
        name="Cleric",
        hit_die=8,
        primary_ability="Wisdom",
        saving_throws=["Wisdom", "Charisma"],
        proficiencies=["simple weapons", "melee weapons"],
    ),
    SRDClass(
        name="Druid",
        hit_die=8,
        primary_ability="Wisdom",
        saving_throws=["Intelligence", "Wisdom"],
        proficiencies=["clubs", "daggers", "darts", "javelins", "maces", "quarterstaffs", "scimitars", "sickles", "slings", "spears"],
    ),
    SRDClass(
        name="Fighter",
        hit_die=10,
        primary_ability="Strength",
        saving_throws=["Strength", "Constitution"],
        proficiencies=["simple weapons", "melee weapons"],
    ),
    SRDClass(
        name="Monk",
        hit_die=8,
        primary_ability="Dexterity",
        saving_throws=["Strength", "Dexterity"],
        proficiencies=["simple weapons", "shortswords"],
    ),
    SRDClass(
        name="Paladin",
        hit_die=10,
        primary_ability="Strength",
        saving_throws=["Wisdom", "Charisma"],
        proficiencies=["simple weapons", "melee weapons"],
    ),
    SRDClass(
        name="Ranger",
        hit_die=10,
        primary_ability="Dexterity",
        saving_throws=["Strength", "Dexterity"],
        proficiencies=["simple weapons", "melee weapons", "martial weapons"],
    ),
    SRDClass(
        name="Rogue",
        hit_die=8,
        primary_ability="Dexterity",
        saving_throws=["Dexterity", "Intelligence"],
        proficiencies=["daggers", "darts", "hand crossbows", "rapiers", "shortswords"],
    ),
    SRDClass(
        name="Sorcerer",
        hit_die=6,
        primary_ability="Charisma",
        saving_throws=["Charisma", "Constitution"],
        proficiencies=["daggers", "darts", "slings", "quarterstaffs", "light crossbows"],
    ),
    SRDClass(
        name="Warlock",
        hit_die=8,
        primary_ability="Charisma",
        saving_throws=["Wisdom", "Charisma"],
        proficiencies=["simple weapons", "melee weapons"],
    ),
    SRDClass(
        name="Wizard",
        hit_die=6,
        primary_ability="Intelligence",
        saving_throws=["Intelligence", "Wisdom"],
        proficiencies=["daggers", "darts", "slings", "quarterstaffs", "light crossbows"],
    ),
]

# ============================================================================
# RACES (Core SRD races)
# ============================================================================

srd_races: list[SRDRace] = [
    SRDRace(
        name="Human",
        speed=30,
        size="Medium",
        ability_bonuses={"Strength": 1, "Dexterity": 1, "Constitution": 1, "Intelligence": 1, "Wisdom": 1, "Charisma": 1},
        traits=["Languages", "Extra Feat"],
    ),
    SRDRace(
        name="Elf",
        speed=30,
        size="Medium",
        ability_bonuses={"Dexterity": 2, "Intelligence": 1},
        traits=["Darkvision", "Keen Senses", "Fey Ancestry", "Trance"],
    ),
    SRDRace(
        name="Dwarf",
        speed=25,
        size="Medium",
        ability_bonuses={"Constitution": 2, "Wisdom": 1},
        traits=["Darkvision", "Dwarven Resilience", "Dwarven Combat Training", "Stonecunning"],
    ),
    SRDRace(
        name="Halfling",
        speed=25,
        size="Small",
        ability_bonuses={"Dexterity": 2, "Charisma": 1},
        traits=["Lucky", "Brave", "Halfling Nimbleness"],
    ),
    SRDRace(
        name="Dragonborn",
        speed=30,
        size="Medium",
        ability_bonuses={"Strength": 2, "Charisma": 1},
        traits=["Draconic Ancestry", "Breath Weapon", "Damage Resistance"],
    ),
    SRDRace(
        name="Gnome",
        speed=25,
        size="Small",
        ability_bonuses={"Intelligence": 2, "Dexterity": 1},
        traits=["Darkvision", "Gnome Cunning", "Speak with Small Beasts"],
    ),
    SRDRace(
        name="Half-Elf",
        speed=30,
        size="Medium",
        ability_bonuses={"Charisma": 2, "Strength": 1, "Intelligence": 1},
        traits=["Darkvision", "Keen Senses", "Fey Ancestry"],
    ),
    SRDRace(
        name="Half-Orc",
        speed=30,
        size="Medium",
        ability_bonuses={"Strength": 2, "Constitution": 1, "Charisma": -2},
        traits=["Darkvision", "Menacing", "Relentless Endurance"],
    ),
    SRDRace(
        name="Tiefling",
        speed=30,
        size="Medium",
        ability_bonuses={"Charisma": 2, "Intelligence": 1},
        traits=["Darkvision", "Hellish Resistance", "Infernal Legacy"],
    ),
]
